CREATE TABLE `activities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`dealId` int,
	`contactId` int,
	`type` enum('meeting','call','email','note','research','other') NOT NULL,
	`subject` varchar(500),
	`description` text,
	`outcome` text,
	`activityDate` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `activities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`title` varchar(255),
	`organization` varchar(255),
	`email` varchar(320),
	`phone` varchar(50),
	`linkedinUrl` varchar(500),
	`relationshipType` enum('owner','executive','advisor','banker','lawyer','agent','other'),
	`relationshipStrength` enum('weak','moderate','strong','very_strong') DEFAULT 'moderate',
	`relevantToDeals` text,
	`expertise` text,
	`notes` text,
	`lastContactDate` timestamp,
	`nextFollowUpDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`league` varchar(255),
	`country` varchar(100),
	`sport` varchar(100) NOT NULL DEFAULT 'football',
	`status` enum('monitoring','warm','active','offer_stage','due_diligence','closed_won','closed_lost','on_hold') NOT NULL DEFAULT 'monitoring',
	`conviction` enum('low','medium','high','very_high') DEFAULT 'medium',
	`priority` int DEFAULT 3,
	`currentValuation` text,
	`revenue` text,
	`ebitda` text,
	`debt` text,
	`currentOwner` text,
	`ownershipStructure` text,
	`minorityStakeAvailable` int DEFAULT 0,
	`targetStakePercentage` text,
	`mediaRightsExpiry` timestamp,
	`lastContactDate` timestamp,
	`nextFollowUpDate` timestamp,
	`investmentThesis` text,
	`keyRisks` text,
	`valueCreationOpportunities` text,
	`privateNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `intelligence` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealId` int,
	`userId` int NOT NULL,
	`type` enum('financial_data','news','ownership_change','management_change','media_rights','sponsorship','transfer_activity','other') NOT NULL,
	`title` varchar(500) NOT NULL,
	`content` text,
	`sourceUrl` varchar(1000),
	`sourceType` varchar(100),
	`relevance` enum('low','medium','high') DEFAULT 'medium',
	`intelligenceDate` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `intelligence_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scenarios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealId` int NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`entryValuation` text NOT NULL,
	`entryMultiple` text,
	`stakePercentage` text NOT NULL,
	`investmentAmount` text NOT NULL,
	`debtPercentage` text DEFAULT ('0'),
	`revenueGrowthRate` text DEFAULT ('5'),
	`ebitdaMarginImprovement` text DEFAULT ('0'),
	`exitYear` int DEFAULT 5,
	`exitMultiple` text,
	`exitValuation` text,
	`irr` text,
	`moic` text,
	`cashOnCashReturn` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scenarios_id` PRIMARY KEY(`id`)
);
